backend:
  name: git-gateway
  branch: main

collections:
  - name: news
    label: Noticias
    folder: news
    create: true
    fields:
      - { name: title, label: TÃ­tulo }
      - { name: image, label: Imagen, widget: image }
      - { name: body, label: Contenido, widget: markdown }
